# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-18 13:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qa', '0003_auto_20160918_1239'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='rating',
            field=models.IntegerField(null=True),
        ),
    ]
